/* tslint:disable */
/* eslint-disable */
/**
 * Davgus Ambulance API
 * Patient, department and placement management for Davgus ambulance UI
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: your_email@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface PatientCreateRequest
 */
export interface PatientCreateRequest {
    /**
     * 
     * @type {string}
     * @memberof PatientCreateRequest
     */
    name: string;
    /**
     * 
     * @type {Date}
     * @memberof PatientCreateRequest
     */
    birthDate: Date;
    /**
     * 
     * @type {string}
     * @memberof PatientCreateRequest
     */
    insuranceId: string;
    /**
     * 
     * @type {string}
     * @memberof PatientCreateRequest
     */
    insuranceCompany: string;
    /**
     * 
     * @type {string}
     * @memberof PatientCreateRequest
     */
    phone: string;
    /**
     * 
     * @type {string}
     * @memberof PatientCreateRequest
     */
    email: string;
    /**
     * 
     * @type {boolean}
     * @memberof PatientCreateRequest
     */
    archived?: boolean;
}

/**
 * Check if a given object implements the PatientCreateRequest interface.
 */
export function instanceOfPatientCreateRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "name" in value;
    isInstance = isInstance && "birthDate" in value;
    isInstance = isInstance && "insuranceId" in value;
    isInstance = isInstance && "insuranceCompany" in value;
    isInstance = isInstance && "phone" in value;
    isInstance = isInstance && "email" in value;

    return isInstance;
}

export function PatientCreateRequestFromJSON(json: any): PatientCreateRequest {
    return PatientCreateRequestFromJSONTyped(json, false);
}

export function PatientCreateRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): PatientCreateRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'birthDate': (new Date(json['birthDate'])),
        'insuranceId': json['insuranceId'],
        'insuranceCompany': json['insuranceCompany'],
        'phone': json['phone'],
        'email': json['email'],
        'archived': !exists(json, 'archived') ? undefined : json['archived'],
    };
}

export function PatientCreateRequestToJSON(value?: PatientCreateRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'birthDate': (value.birthDate.toISOString().substr(0,10)),
        'insuranceId': value.insuranceId,
        'insuranceCompany': value.insuranceCompany,
        'phone': value.phone,
        'email': value.email,
        'archived': value.archived,
    };
}

