/* tslint:disable */
/* eslint-disable */
/**
 * Davgus Ambulance API
 * Patient, department and placement management for Davgus ambulance UI
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: your_email@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Placement
 */
export interface Placement {
    /**
     * 
     * @type {string}
     * @memberof Placement
     */
    id: string;
    /**
     * 
     * @type {string}
     * @memberof Placement
     */
    patientId: string;
    /**
     * 
     * @type {string}
     * @memberof Placement
     */
    patientName: string;
    /**
     * 
     * @type {string}
     * @memberof Placement
     */
    departmentId: string;
    /**
     * 
     * @type {string}
     * @memberof Placement
     */
    departmentName: string;
    /**
     * 
     * @type {string}
     * @memberof Placement
     */
    roomId: string;
    /**
     * 
     * @type {string}
     * @memberof Placement
     */
    roomNumber: string;
    /**
     * 
     * @type {Date}
     * @memberof Placement
     */
    admissionDate: Date;
    /**
     * 
     * @type {string}
     * @memberof Placement
     */
    notes: string;
}

/**
 * Check if a given object implements the Placement interface.
 */
export function instanceOfPlacement(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "patientId" in value;
    isInstance = isInstance && "patientName" in value;
    isInstance = isInstance && "departmentId" in value;
    isInstance = isInstance && "departmentName" in value;
    isInstance = isInstance && "roomId" in value;
    isInstance = isInstance && "roomNumber" in value;
    isInstance = isInstance && "admissionDate" in value;
    isInstance = isInstance && "notes" in value;

    return isInstance;
}

export function PlacementFromJSON(json: any): Placement {
    return PlacementFromJSONTyped(json, false);
}

export function PlacementFromJSONTyped(json: any, ignoreDiscriminator: boolean): Placement {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'patientId': json['patientId'],
        'patientName': json['patientName'],
        'departmentId': json['departmentId'],
        'departmentName': json['departmentName'],
        'roomId': json['roomId'],
        'roomNumber': json['roomNumber'],
        'admissionDate': (new Date(json['admissionDate'])),
        'notes': json['notes'],
    };
}

export function PlacementToJSON(value?: Placement | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'patientId': value.patientId,
        'patientName': value.patientName,
        'departmentId': value.departmentId,
        'departmentName': value.departmentName,
        'roomId': value.roomId,
        'roomNumber': value.roomNumber,
        'admissionDate': (value.admissionDate.toISOString().substr(0,10)),
        'notes': value.notes,
    };
}

