/* tslint:disable */
/* eslint-disable */
/**
 * Davgus Ambulance API
 * Patient, department and placement management for Davgus ambulance UI
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: your_email@stuba.sk
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  Placement,
  PlacementCreateRequest,
} from '../models';
import {
    PlacementFromJSON,
    PlacementToJSON,
    PlacementCreateRequestFromJSON,
    PlacementCreateRequestToJSON,
} from '../models';

export interface CreatePlacementRequest {
    placementCreateRequest: PlacementCreateRequest;
}

export interface DeletePlacementRequest {
    placementId: string;
}

export interface GetPlacementRequest {
    placementId: string;
}

export interface GetPlacementForPatientRequest {
    patientId: string;
}

export interface UpdatePlacementRequest {
    placementId: string;
    placement: Placement;
}

/**
 * PlacementsApi - interface
 * 
 * @export
 * @interface PlacementsApiInterface
 */
export interface PlacementsApiInterface {
    /**
     * Creates a placement with generated identifier.
     * @summary Create placement
     * @param {PlacementCreateRequest} placementCreateRequest Placement to create
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PlacementsApiInterface
     */
    createPlacementRaw(requestParameters: CreatePlacementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Placement>>;

    /**
     * Creates a placement with generated identifier.
     * Create placement
     */
    createPlacement(requestParameters: CreatePlacementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Placement>;

    /**
     * Deletes one placement by id.
     * @summary Delete placement
     * @param {string} placementId Placement identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PlacementsApiInterface
     */
    deletePlacementRaw(requestParameters: DeletePlacementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>>;

    /**
     * Deletes one placement by id.
     * Delete placement
     */
    deletePlacement(requestParameters: DeletePlacementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void>;

    /**
     * Returns one placement by id.
     * @summary Get placement by id
     * @param {string} placementId Placement identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PlacementsApiInterface
     */
    getPlacementRaw(requestParameters: GetPlacementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Placement>>;

    /**
     * Returns one placement by id.
     * Get placement by id
     */
    getPlacement(requestParameters: GetPlacementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Placement>;

    /**
     * Returns current placement for a given patient.
     * @summary Get placement for patient
     * @param {string} patientId Patient identifier
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PlacementsApiInterface
     */
    getPlacementForPatientRaw(requestParameters: GetPlacementForPatientRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Placement>>;

    /**
     * Returns current placement for a given patient.
     * Get placement for patient
     */
    getPlacementForPatient(requestParameters: GetPlacementForPatientRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Placement>;

    /**
     * Returns all active patient placements.
     * @summary Get all placements
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PlacementsApiInterface
     */
    getPlacementsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Placement>>>;

    /**
     * Returns all active patient placements.
     * Get all placements
     */
    getPlacements(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Placement>>;

    /**
     * Updates a placement.
     * @summary Update placement
     * @param {string} placementId Placement identifier
     * @param {Placement} placement Full placement object to update
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PlacementsApiInterface
     */
    updatePlacementRaw(requestParameters: UpdatePlacementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Placement>>;

    /**
     * Updates a placement.
     * Update placement
     */
    updatePlacement(requestParameters: UpdatePlacementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Placement>;

}

/**
 * 
 */
export class PlacementsApi extends runtime.BaseAPI implements PlacementsApiInterface {

    /**
     * Creates a placement with generated identifier.
     * Create placement
     */
    async createPlacementRaw(requestParameters: CreatePlacementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Placement>> {
        if (requestParameters.placementCreateRequest === null || requestParameters.placementCreateRequest === undefined) {
            throw new runtime.RequiredError('placementCreateRequest','Required parameter requestParameters.placementCreateRequest was null or undefined when calling createPlacement.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/placements`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: PlacementCreateRequestToJSON(requestParameters.placementCreateRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlacementFromJSON(jsonValue));
    }

    /**
     * Creates a placement with generated identifier.
     * Create placement
     */
    async createPlacement(requestParameters: CreatePlacementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Placement> {
        const response = await this.createPlacementRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Deletes one placement by id.
     * Delete placement
     */
    async deletePlacementRaw(requestParameters: DeletePlacementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.placementId === null || requestParameters.placementId === undefined) {
            throw new runtime.RequiredError('placementId','Required parameter requestParameters.placementId was null or undefined when calling deletePlacement.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/placements/{placementId}`.replace(`{${"placementId"}}`, encodeURIComponent(String(requestParameters.placementId))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     * Deletes one placement by id.
     * Delete placement
     */
    async deletePlacement(requestParameters: DeletePlacementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<void> {
        await this.deletePlacementRaw(requestParameters, initOverrides);
    }

    /**
     * Returns one placement by id.
     * Get placement by id
     */
    async getPlacementRaw(requestParameters: GetPlacementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Placement>> {
        if (requestParameters.placementId === null || requestParameters.placementId === undefined) {
            throw new runtime.RequiredError('placementId','Required parameter requestParameters.placementId was null or undefined when calling getPlacement.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/placements/{placementId}`.replace(`{${"placementId"}}`, encodeURIComponent(String(requestParameters.placementId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlacementFromJSON(jsonValue));
    }

    /**
     * Returns one placement by id.
     * Get placement by id
     */
    async getPlacement(requestParameters: GetPlacementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Placement> {
        const response = await this.getPlacementRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns current placement for a given patient.
     * Get placement for patient
     */
    async getPlacementForPatientRaw(requestParameters: GetPlacementForPatientRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Placement>> {
        if (requestParameters.patientId === null || requestParameters.patientId === undefined) {
            throw new runtime.RequiredError('patientId','Required parameter requestParameters.patientId was null or undefined when calling getPlacementForPatient.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/patients/{patientId}/placement`.replace(`{${"patientId"}}`, encodeURIComponent(String(requestParameters.patientId))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlacementFromJSON(jsonValue));
    }

    /**
     * Returns current placement for a given patient.
     * Get placement for patient
     */
    async getPlacementForPatient(requestParameters: GetPlacementForPatientRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Placement> {
        const response = await this.getPlacementForPatientRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     * Returns all active patient placements.
     * Get all placements
     */
    async getPlacementsRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<Placement>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/placements`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(PlacementFromJSON));
    }

    /**
     * Returns all active patient placements.
     * Get all placements
     */
    async getPlacements(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<Placement>> {
        const response = await this.getPlacementsRaw(initOverrides);
        return await response.value();
    }

    /**
     * Updates a placement.
     * Update placement
     */
    async updatePlacementRaw(requestParameters: UpdatePlacementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Placement>> {
        if (requestParameters.placementId === null || requestParameters.placementId === undefined) {
            throw new runtime.RequiredError('placementId','Required parameter requestParameters.placementId was null or undefined when calling updatePlacement.');
        }

        if (requestParameters.placement === null || requestParameters.placement === undefined) {
            throw new runtime.RequiredError('placement','Required parameter requestParameters.placement was null or undefined when calling updatePlacement.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/placements/{placementId}`.replace(`{${"placementId"}}`, encodeURIComponent(String(requestParameters.placementId))),
            method: 'PUT',
            headers: headerParameters,
            query: queryParameters,
            body: PlacementToJSON(requestParameters.placement),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => PlacementFromJSON(jsonValue));
    }

    /**
     * Updates a placement.
     * Update placement
     */
    async updatePlacement(requestParameters: UpdatePlacementRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Placement> {
        const response = await this.updatePlacementRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
