/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface DavgusAmbulanceWlApp {
    }
}
declare global {
    interface HTMLDavgusAmbulanceWlAppElement extends Components.DavgusAmbulanceWlApp, HTMLStencilElement {
    }
    var HTMLDavgusAmbulanceWlAppElement: {
        prototype: HTMLDavgusAmbulanceWlAppElement;
        new (): HTMLDavgusAmbulanceWlAppElement;
    };
    interface HTMLElementTagNameMap {
        "davgus-ambulance-wl-app": HTMLDavgusAmbulanceWlAppElement;
    }
}
declare namespace LocalJSX {
    interface DavgusAmbulanceWlApp {
    }
    interface IntrinsicElements {
        "davgus-ambulance-wl-app": DavgusAmbulanceWlApp;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "davgus-ambulance-wl-app": LocalJSX.IntrinsicElements["davgus-ambulance-wl-app"] & JSXBase.HTMLAttributes<HTMLDavgusAmbulanceWlAppElement>;
        }
    }
}
